//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireHub.Shared.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HireHub.Shared.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for role {0} on resource {1}.
        /// </summary>
        internal static string Auth_AccessDenied {
            get {
                return ResourceManager.GetString("Auth_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials for user {0}.
        /// </summary>
        internal static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has exceeded maximum login attempts ({1}).
        /// </summary>
        internal static string Auth_MaxLoginAttemptsExceeded {
            get {
                return ResourceManager.GetString("Auth_MaxLoginAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least {0} uppercase, {1} lowercase, and {2} special characters.
        /// </summary>
        internal static string Auth_PasswordComplexity {
            get {
                return ResourceManager.GetString("Auth_PasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found in directory {1}.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation {0} failed due to {1}.
        /// </summary>
        internal static string Error_OperationFailed {
            get {
                return ResourceManager.GetString("Error_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing {0}: {1}.
        /// </summary>
        internal static string Error_ProcessingFailed {
            get {
                return ResourceManager.GetString("Error_ProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} returned status code {1}.
        /// </summary>
        internal static string Error_ServiceResponse {
            get {
                return ResourceManager.GetString("Error_ServiceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a date after {1}.
        /// </summary>
        internal static string Validation_DateAfter {
            get {
                return ResourceManager.GetString("Validation_DateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a date before {1}.
        /// </summary>
        internal static string Validation_DateBefore {
            get {
                return ResourceManager.GetString("Validation_DateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be within the range {1} to {2}.
        /// </summary>
        internal static string Validation_DateRange {
            get {
                return ResourceManager.GetString("Validation_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be earlier than {1}.
        /// </summary>
        internal static string Validation_DateTooEarly {
            get {
                return ResourceManager.GetString("Validation_DateTooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not exceed {1} characters.
        /// </summary>
        internal static string Validation_MaxLengthExceeded {
            get {
                return ResourceManager.GetString("Validation_MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters long.
        /// </summary>
        internal static string Validation_MinLengthRequired {
            get {
                return ResourceManager.GetString("Validation_MinLengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid number between {1} and {2}.
        /// </summary>
        internal static string Validation_NumberRange {
            get {
                return ResourceManager.GetString("Validation_NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than {1} or greater than {2}.
        /// </summary>
        internal static string Validation_OutOfBounds {
            get {
                return ResourceManager.GetString("Validation_OutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        internal static string Validation_RangeBetween {
            get {
                return ResourceManager.GetString("Validation_RangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid time format (e.g., {1}).
        /// </summary>
        internal static string Validation_TimeFormat {
            get {
                return ResourceManager.GetString("Validation_TimeFormat", resourceCulture);
            }
        }
    }
}
